{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.apace100",
    "module": "apoli",
    "version": "2.12.0-pre.2+mc.1.21.1-morgan",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.ladysnake",
          "module": "PlayerAbilityLib",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.apace100",
          "module": "calio",
          "version": {
            "requires": "1.14.0+mc.1.21.x"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.127"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "additionalentityattributes",
          "version": {
            "requires": "1.8.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "apoli-2.12.0-pre.2+mc.1.21.1-morgan.jar",
          "url": "apoli-2.12.0-pre.2+mc.1.21.1-morgan.jar",
          "size": 4309120,
          "sha512": "708ad13b8ebb6513be3d98492ecf7c727ac78185bca760e28612e31c27b5528de42b504f156d3e10a49f325688b41d919a6674544b98f1ef997ef3a6012f2fca",
          "sha256": "2fda9302eb81791f141c36cac7bcc62659a55e93e36e18c8fd748bbea66d39ec",
          "sha1": "1671a0cc00b2a111ea8842cd4c14b44587f17a85",
          "md5": "8ec13926c84a9de435cdc85f08edd207"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.demonwav.mcdev",
          "module": "annotations",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.ladysnake",
          "module": "PlayerAbilityLib",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.apace100",
          "module": "calio",
          "version": {
            "requires": "1.14.0+mc.1.21.x"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.127"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "additionalentityattributes",
          "version": {
            "requires": "1.8.0+1.21"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "apoli-2.12.0-pre.2+mc.1.21.1-morgan.jar",
          "url": "apoli-2.12.0-pre.2+mc.1.21.1-morgan.jar",
          "size": 4309120,
          "sha512": "708ad13b8ebb6513be3d98492ecf7c727ac78185bca760e28612e31c27b5528de42b504f156d3e10a49f325688b41d919a6674544b98f1ef997ef3a6012f2fca",
          "sha256": "2fda9302eb81791f141c36cac7bcc62659a55e93e36e18c8fd748bbea66d39ec",
          "sha1": "1671a0cc00b2a111ea8842cd4c14b44587f17a85",
          "md5": "8ec13926c84a9de435cdc85f08edd207"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apoli-2.12.0-pre.2+mc.1.21.1-morgan-sources.jar",
          "url": "apoli-2.12.0-pre.2+mc.1.21.1-morgan-sources.jar",
          "size": 823686,
          "sha512": "4cbeab423cc08a072e30f3fe707962a884b4e23bc88ddb7be3ddb979729bfdd9e2441743247363354d485c4984e607ee41d6279a1b490a37c33c90d663ff722e",
          "sha256": "47a21cf5493eeab9bc936ea2d4edb0772a056e50261e4082fbf89554d71823af",
          "sha1": "e5bcf4bff39be67c6b30b597fbb07b2604959d80",
          "md5": "7a65f9fd45f758c1da613d4e40292fc5"
        }
      ]
    }
  ]
}
